Repository caio-imperial/gopher-economy, pull requests merged in 2025-02, with the labels that each got.

#16 Add function to remove multiples space in message
  README.md
  bot/bot.go
Labels: bug, good first issue

#17 13 Add command !git
  README.md
  bot/bot.go
Labels: enhancement, good first issue

#22 Added !git in README.md with a better description
  README.md
Labels: documentation, good first issue
